version: 2.1
orbs:
  slack: circleci/slack@4.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: make
      - slack/notify:
          channel: C034YBSS9HU
          event: fail
          template: basic_fail_1
workflows:
  build-workflow:
    jobs:
      - build
